### ISSUE TITLE
[1.14-fabirc] Actively written-to RAM module keeps modifying ROM module

### ISSUE THREAD

**Issue by Sturmlilie** [MightyPirates/TIS-3D#102]
Environment: Dedicated server, creative mode
How to reproduce: Put an execution and RAM module side-by-side and load the following test program:

```
# RAMTEST
#DEFINE RAM ANY
MOV 0, ACC
SAV
LOOP:
SWP
MOV ACC, RAM
MOV ACC, RAM
ADD 1
SAV
SUB 0XFF
JNZ LOOP
END: JMP END
```
It will start filling up the RAM module. Then take a ROM module, and use shift-click to copy the current contents of the RAM. While the RAM continues being written to, the held ROM module will cause hand-motion, and the memory view suggests that the new values arriving in RAM are also being written to the ROM module.

Couldn't reproduce this in survival because the shift-click doesn't work there (only opens memory view).

**Comment by fnuecke** [comment]
I could've sworn there was a time when NBTByteArray always created a copy of the data... but apparently not, huh.

Thanks! Will fix.

That copying doesn't work in survival sounds like a bug that came in in the 1.14 port... will also have a look at that.
