### ISSUE TITLE
[1.14-fabric] RAM, ROM, random module combination causes server crash

### ISSUE THREAD

**Issue by Sturmlilie** [MightyPirates/TIS-3D#103]
Environment: Dedicated server, creative mode
How to reproduce: Build the following topology while the controller is powered down:
```
[R] random module
[A] RAM module
[O] ROM module

   [R][R]
[R][A][O]
   [R][R]
```

Then turn the controller on. The server will instantly crash with the following stack trace: https://gist.github.com/Sturmlilie/819ed062d81f8a5cf10393fd3f2edd45

Restarting the world is impossible without NBT editing or similar because the server will instantly crash again upon ticking the world.

**Comment by fnuecke** [comment]
Oh wow, yep, that's definitely missing a check. Shows how well used that module is I guess...

Thanks! Will fix and merge through the branches.
