### ISSUE TITLE
Are the RAM/ROM modules working?

### ISSUE THREAD

**Issue by ComputerJock** [MightyPirates/TIS-3D#126]
Execution module on top of RAM module

Loading the RAM:
mov 0,down
mov 10,down
mov 1,down
mov 8,down
mov 2,down
mov 6,down
mov 3,down
mov 8,down
mov 4,down
mov 10,down
mov 5,down
mov 10,down
mov 6,down
mov 10,down
mov 7,down
mov 8,down
mov 8,down
mov 8,down
jro 0

I wait for the above program to halt

I then right-click (use) the RAM module while holding a ROM module (I also tried left-clicking)

If I then point the ROM module away and right-click, I get a display that apparently shows the contents of the module. I see all zeros.

What am I doing wrong?
Win7x64, Minecraft 1.16.4, Java E:/Program Files (x86)/Minecraft/runtime/jre-x64/bin/javaw.exe

**Comment by Sturmlilie** [comment]
If you are looking at an installed RAM module, and are holding a ROM module in your hand, the following actions are possible: Plain right click -> copy contents of the held ROM onto the installed RAM.
Crouch right click -> copy contents of the installed RAM onto the held ROM.

**Comment by fnuecke** [comment]
Yeah, sneak right click is copy to ROM. And that that still seems to work :)

**Comment by unforseenconsequ3nces** [comment]
> 
> 
> Yeah, sneak right click is copy to ROM. And that that still seems to work :)

Don't think I didn't notice the extra "that" >:^)
