### ISSUE TITLE
left and right are swaped?

### ISSUE THREAD

**Issue by SalTeyJek004** [MightyPirates/TIS-3D#129]
i was trying to get the display module example code working, but it wouldn't work unless the display was to the right of the execution module.
the other mods i have are immersive portals, pehkui, ok zoomer, lithium, and firstperson model on fabric 1.16.4.

here is an image from my world with other mods
![2020-12-27_22 32 09](https://user-images.githubusercontent.com/53840187/103194154-842f0b00-4893-11eb-8e80-7764b43b192d.png)

here is an image with no other mods
![2020-12-27_22 42 34](https://user-images.githubusercontent.com/53840187/103194645-213e7380-4895-11eb-96fb-95eb67642356.png)

**Comment by fnuecke** [comment]
Hey, sorry about that, this slid in with a pull request a few versions ago and nobody noticed. Fixed as of 4500d145a6244d6a5c1fa1904eb8938ebae31c38, update on Curse is on the way.

**Comment by unforseenconsequ3nces** [comment]
Actually, right is technically **right** because you are sending it to >> right not << left
Sorry if I didn't understand correctly.
