### ISSUE TITLE
Consider adding some more opcodes, specifically bitwise

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/TIS-3D#13]
To make things a little more... practical in the context of Minecraft, consider adding bitwise opcodes like `XOR`, which could be a sane middle ground between what's in now (pure TIS-100) and adding comparatively high level stuff like `MUL` or `DIV`.

**Comment by ds84182** [comment]
See #14

**Comment by fnuecke** [comment]
9a716af5ddb2c0426b575ccb223be3077ecbff4f
