### ISSUE TITLE
1.16.4 compability?

### ISSUE THREAD

**Issue by Edwelde** [MightyPirates/TIS-3D#130]
i tried mod for 1.16.2 on 1.16.4, it works, but ports are messed, depend on facing of module and aren't consistent.
.4 and .3 patches don't seem to change anything relevant, but i dont know if mod behaves properly on .2

**Comment by fnuecke** [comment]
Hey, sorry about that, this slid in with a pull request a few versions ago and nobody noticed. Fixed as of 4500d145a6244d6a5c1fa1904eb8938ebae31c38, update on Curse is on the way.
