### ISSUE TITLE
Suggestion: build against 1.16.4 & latest Fabric API/Loader

### ISSUE THREAD

**Issue by ComputerJock** [MightyPirates/TIS-3D#131]
Since many people (myself included) have moved to 1.16.4, would you consider building TIS-3D against 1.16.4 and the latest Fabric API/Loader?

I have no idea of the effort involved so I will not mind at all if you ignore this suggestion.

Thanks for the mod -- it is quite fun.

**Comment by fnuecke** [comment]
Sorry, but 1.16.5 is the only 1.16 version supported. No plans to backport.
