### ISSUE TITLE
Suggestion: Increase the casing limit

### ISSUE THREAD

**Issue by immibis** [MightyPirates/TIS-3D#132]
So I just finished TIS-100 the other day and after coming back to Minecraft, the limit of 8 casings feels a bit weird, considering the average TIS-100 grid has 12 nodes, plus inputs and outputs.

Yes, you can wrap around to the other side, but I feel like you should at least be able to replicate the 4x3 grid from TIS-100, without having to go around a corner, you know? Accounting for inputs and outputs, the limit should be more like 15.

Is there a technical reason to make it low or is it just balance? I don't see why it shouldn't be even higher, like 32

**Comment by Szasdragon** [comment]
In the config you can modify the "maximum number of casings a single controller supports". It can be up to 512, but I don't think it is necessary, and possible cause lag.
I changed to 16 and it is enough for many computer which I built. Code efficiency and minimizing the build is good practice. Or build multiple computer for each specialized purpose.

**Comment by immibis** [comment]
Mods should come with good default configs, you shouldn't have to change them to be good

**Comment by fnuecke** [comment]
It was a pretty arbitrary choice. And performance paranoia. Did some testing, and any internal stuff seems to do just fine (pumping out new redstone signals every frame is a different topic, but that's already abusable with 8, so eh). So I'm totally fine with bumping the default to 16.
