### ISSUE TITLE
UI Rendering bug in ROM module

### ISSUE THREAD

**Issue by zack-emmert** [MightyPirates/TIS-3D#138]
It appears that the background section of the ROM module UI follows my cursor. I'm pretty sure this isn't supposed to be happening.
![render_bug](https://user-images.githubusercontent.com/12279880/125507658-463f4e75-3e3a-4a2c-bcf1-04947c705a8c.gif) 

Tested on version 1.6.2+12.

**Comment by fnuecke** [comment]
Ah, the joys of changing mappings. Thanks for reporting! Fixed in version 1.6.3.

**Comment by unforseenconsequ3nces** [comment]
How do you even enable that UI?

**Comment by fnuecke** [comment]
Craft a ROM module, right click while holding it.
