### ISSUE TITLE
Why can you not concatenate programs from multiple pages in a code bible? (1.12.2 Forge)

### ISSUE THREAD

**Issue by unforseenconsequ3nces** [MightyPirates/TIS-3D#140]
I know, this is not really an issue but I am trying to make an interpreter. The one ploblem is that, I cannot seem to get multiple pages working on an execution module from a code bible. It's extremely annoying.

Other than that, great mod, great work, I am also willing to work with this mod using opencomputers, Any idea what I can do to get it working?

**Comment by Sturmlilie** [comment]
Try putting #BWTM as the last line of the page you want to be continued (maximum is still 3 pages though).

**Comment by unforseenconsequ3nces** [comment]
Oh, thanks. That's just enough for me, the other execution modules should be able to handle everything else.

**Comment by unforseenconsequ3nces** [comment]
What does BWTM even stand for anyway.. also any documentation for 6507 assembly?

**Comment by fnuecke** [comment]
`#BWTM` = "But way, there's more" :)

> also any documentation for 6507 assembly?

Not sure what you mean? All the opcodes should be documented in the manual's entry on the execution module.

**Comment by unforseenconsequ3nces** [comment]
Ah, okay. Didn't expect a comment from the developer.
