### ISSUE TITLE
[Bug] [1.12.2 Forge] Loops break, apparently...

### ISSUE THREAD

**Issue by unforseenconsequ3nces** [MightyPirates/TIS-3D#142]
Well, as the title says...
![image](https://user-images.githubusercontent.com/88140035/128639657-7859a9e7-dd27-48b8-b5b2-ce580644d380.png)

Yup, the loop does not work, and I know for a fact that's valid opcode. It also fails on an execution module which is also more fustrating :^) _thinks about life choices_.

**Comment by fnuecke** [comment]
What does the tooltip say? Could it be an error on the previous page?

**Comment by unforseenconsequ3nces** [comment]
No, it's the first page. It says `invalid opcode`.
Currently trying to fix garry the robot who is saying thank you for helping me.

**Comment by unforseenconsequ3nces** [comment]
I have gotten the same error again:
![image](https://user-images.githubusercontent.com/88140035/128641921-3e0d78a7-7398-43ee-a86d-c6e42ecbb7d0.png)

Pretty annoying at times.

**Comment by unforseenconsequ3nces** [comment]
NEW INFORMATION right after:
putting a "?" symbol and then the ":" symbol back fixes it.
![image](https://user-images.githubusercontent.com/88140035/128641967-37d893dd-5bc1-4961-87ad-29e3608d3408.png)

**Comment by fnuecke** [comment]
I'm afraid I cannot reproduce this and have no idea what it could be. I'm suspecting something about how your OS input works might potentially result in special characters? Wildly guessing here. So yeah, I'm afraid I can't help you here.
