### ISSUE TITLE
IF statements in TIS-3D?

### ISSUE THREAD

**Issue by unforseenconsequ3nces** [MightyPirates/TIS-3D#143]
How do I check if `ACC` is equal to a integer? I have been searching for something like JFE *Jump if.. is equal to..* or something, but no luck.

**Comment by Sturmlilie** [comment]
There should be branch instructions that act on the zero flag (so you'd sub whatever you want to compare).

**Comment by unforseenconsequ3nces** [comment]
Working, thanks.
