### ISSUE TITLE
[Forge 1.16.5][bug] Crash on attempting to break modules

### ISSUE THREAD

**Issue by Maxwell45** [MightyPirates/TIS-3D#145]
Title says it all. I tried breaking down modules (left click) in survival mode, which then promptly lead to the game crashing, log attached below. Tried to do that multiple times with same results. Breaking the casing blocks in creative works perfectly fine, interestingly enough.

I still love the mod, though. Had a blast with TIS-100, glad it's been extended upon in MC. Thanks for all the hard work, guys!

Upd1: Attempting to break casings/controllers in survival also crashes the game for me

[2021-08-27-1.log](https://github.com/MightyPirates/TIS-3D/files/7066088/2021-08-27-1.log)

**Comment by fnuecke** [comment]
Thanks so much for reporting, and apologies for the delay. Should be fixed in the next version :)
