### ISSUE TITLE
[Feature Request] Code Bible in Lowercase; Export code.

### ISSUE THREAD

**Issue by duncanwebb** [MightyPirates/TIS-3D#146]
TIS-3D-MC1.16.2-Fabric-1.6.1.23
TIS-3D-Additions-0.2.1+1.16.2

It would be nice if the code bibles show the code in lowercase, as it is easier to read than all uppercase. Would make numbers clearer, too.

Where are is the data for the code bibles stored, can it be export as text? This would be good for sharing and bug reporting.

**Comment by fnuecke** [comment]
Added a client-side option to disable the automatic upper-case conversion.

You can copy code back out using regular copy-paste (e.g. select then ctrl+c on Windows).

**Comment by esotericist** [comment]
pasting code from the code bible to an execution module with right click, then copying it back with shift-right click, converts it all back to uppercase again.

it might be useful to have an explicit setting for "i want my code bible to be lowercase, always", especially to simplify reuse of snippets from someone else. if we ever have people sharing code.

alternately, a hotkey combo in the code bible that does case conversion could work, maybe?

**Comment by fnuecke** [comment]
If this becomes an actual, pressing concern for someone, maybe. Until then I'd like to avoid every step towards making the code bible an IDE (yes yes, overly dramatic :P)

**Comment by esotericist** [comment]
i mean. i was excited to have lowercase code then ran into that behavior and was sad, so it was an actual concern for me. :p but not pressing, no.
