### ISSUE TITLE
Adjacent Redstone Dust affects Controller

### ISSUE THREAD

**Issue by duncanwebb** [MightyPirates/TIS-3D#147]
TIS-3D-MC1.16.2-Fabric-1.6.1.23
TIS-3D-Additions-0.2.1+1.16.2

The controller has a power 3 redstone, the output of the redstone module affects the speed of the controller.

https://user-images.githubusercontent.com/4198031/138698222-1277c3b6-78ec-484f-80e4-1df4d7bdee7e.mp4

BTW, the documentation does not explain the difference between the two gauges on the redstone module, I assume that one is from the execution module and the other is the external signal.

Interesting mod, could do with numerous real-world examples. My first program was a rising or falling edge detector.

**Comment by duncanwebb** [comment]
https://user-images.githubusercontent.com/4198031/140606039-3d0f1228-a241-46b1-83ef-3503c9a71df3.mp4

Here is a second example where the computer is emitting a redstone signal of one and the redstone dust is being activated by the controller and feeding itself, so the controller is running.

Is this what is intended?

**Comment by esotericist** [comment]
> The controller has a power 3 redstone, the output of the redstone module affects the speed of the controller.

![image](https://user-images.githubusercontent.com/1569754/144906041-555dbb8b-8fea-4595-be17-b3217da41c9d.png)

that the amount of redstone that enters the controller affects the speed is documented and intended. that the total input value can exceed 15 (with multiple sources) is not documented, but is also intended.

> BTW, the documentation does not explain the difference between the two gauges on the redstone module, I assume that one is from the execution module and the other is the external signal.

one is redstone signal received (down arrow to bar: input from world), one is redstone signal being sent (up arrow from bar: out to world). 

> Here is a second example where the computer is emitting a redstone signal of one and the redstone dust is being activated by the controller and feeding itself, so the controller is running.
> 
> Is this what is intended?

this is a side effect of how redstone functions that makes it difficult to prevent. so it's less 'intended', and more of an emergent property of the world. vanilla redstone contraptions achieve perpetual motion this way, after all.

**Comment by fnuecke** [comment]
That said, I can't repro this with the Forge versions (controller block does *not* act as a "solid" block, transmitting a signal from e.g. a redstone block, there). So I'm suspecting this is a Fabric version bug. Not sure when I'll look into that though, so if someone else wants to dig into this, be my guest.
