### ISSUE TITLE
[1.16.5 onward] infrared module successfully sends packets through entities

### ISSUE THREAD

**Issue by esotericist** [MightyPirates/TIS-3D#150]
as i understand it, the intended behavior is that both blocks and entities block infrared packets. blocks stop the packets, entities do not.

this appears to be a regression from 1.12.2, but i don't understand the capabilities stuff enough to troubleshoot it myself. i did confirm it on all three major release versions, though.

given this and #108 (which appears to still be valid for the forge port) i'm wondering if the infrared module might need some more substantive attention at some point. (hopefully not removal. it's too awesome a concept. :grin: )

**Comment by fnuecke** [comment]
Interestingly the pre-check on whether entities should be considered collidable seems to have changed (idea was to mirror the "is the block transparent" check so that "transparent" entities don't block it, much like glass blocks). Good find!
