### ISSUE TITLE
Suggestion: Prevent adjacent redstone modules from interacting with each other

### ISSUE THREAD

**Issue by AnFazer** [MightyPirates/TIS-3D#157]
Pretty much what it says in the title. I believe this one is obvious and likely have been a highly desired change by many for a long time; still, I should elaborate further.

Currently, two redstone modules put adjacent to each other will be _constantly_ exchanging packets with each other, and are useless at best (whatever value you try to put into one will be near-instantaneously overwritten by the other) and glitching at worst (if there're redstone wires running to each of the modules, powering one will lock both of them into sustaining the signal forever). I can think of a very few instances in which their current behavior is desirable (involving relaying signals unchanged, quickly toggling a signal) and in all these cases it's both easier and cheaper to just use regular redstone.

Removing said interactions, conversely, would allow for making _much_ more compact TIS-based redstone mechanisms with far less overhead, and overall definitely improve the potential for the uses of TIS-3D machines.

Please feel free to request further elaboration and examples, but I expect this issue is pretty self-explanatory and those won't be needed. :3

**Comment by tynberry** [comment]
You can use the key while crouching on the casings to prevent inputs from some directions.
