### ISSUE TITLE
[Suggestion] Different tier programming books with bigger lines limit and creative book with infinite lines

### ISSUE THREAD

**Issue by nostopgmaming17** [MightyPirates/TIS-3D#158]
We should have different tiers of books having bigger and bigger line limits, And creative books with infinite lines

Why we need this: if you want to use the terminal module in any way useful you would need way more lines than tis-3d currently has to offer
Why is that? because they let you type strings instead of numbers

Another good suggestion:
https://github.com/MightyPirates/TIS-3D/issues/156 - #DEFINE for macros

**Comment by walksanatora** [comment]
note: you can use more then 20 lines
if you use a vanilla book

**Comment by fnuecke** [comment]
Sorry, not planning on going that route. A recent PR added the option to disable the line limit in the config, however, maybe that'll help.
