### ISSUE TITLE
39 instruction count limit reasoning/workarounds?

### ISSUE THREAD

**Issue by Olliroxx** [MightyPirates/TIS-3D#160]
Whenever I get to the line before the end of the second page, I get the error "Too many lines". This seems like a super arbitrary limitation, and really stops you from doing anything complicated. Is there a reason behind this? Is there a workaround I'm missing (other than implementing a middle language and reading that from a rom/ram module)?

**Comment by Maxwell45** [comment]
I believe you can increase the maximum amount of lines in the configs of the mod

**Comment by Olliroxx** [comment]
Does this need a rebuild? If not, what command/file should I use?

**Comment by Maxwell45** [comment]
Nope. Just go to your Minecraft installation folder, go to configs folder and look out for the TIS-3D configuration file in particular. Open it up with notepad and change it to whatever you like

**Comment by Olliroxx** [comment]
How would I do this on a server?

**Comment by Maxwell45** [comment]
If you are a server owner there also should be a config folder where you can change some values. Not sure how to circumvent this otherwise though
