### ISSUE TITLE
Terminal screen is bugged. [1.12-forge]

### ISSUE THREAD

**Issue by mewhenthegit** [MightyPirates/TIS-3D#162]
Hello, i noticed when using the terminal module that the GUI is bugged. I tried messing around with my settings but it still stayed.
I'm on a server with Forge 1.12.2 with cc tweaked 1.83.0, OpenComputers 1.7.5.192, DimensionalDoors 3.0.9 and TIS-3D 1.5.1.37. I am also using optifine HD U G5. I have attached a screenshot to what it looks like below.

Thanks in advance
![2022-07-16_09 48 45](https://user-images.githubusercontent.com/66245823/179345982-ca7daace-5273-4031-8c92-d28928ae6021.png)
.

**Comment by asiekierka** [comment]
Does this happen without OptiFine installed?

**Comment by mewhenthegit** [comment]
> Does this happen without OptiFine installed?

Well i guess it's still kind of bugged but it's more usable. I think i just have to disable optifine to input on a terminal, oh well.
![2022-07-16_10 09 38](https://user-images.githubusercontent.com/66245823/195997056-60a57013-9c04-4ebf-a451-9249751f3c0b.png)
