### ISSUE TITLE
(74-mods) Forge on Apex Hosting server crashes on startup.

### ISSUE THREAD

**Issue by Taggart1993** [MightyPirates/TIS-3D#166]
[crash-2022-12-28_04.58.32-fml (1).txt](https://github.com/MightyPirates/TIS-3D/files/10315536/crash-2022-12-28_04.58.32-fml.1.txt)
I start the server and it seems to run fine, but it crashes when it tries to load this mod. I got help from a discord for modding, they said to update the forge version, but I'm not sure how I can do that on Apex, since it just runs on a jar named "Forge_1.16.5.jar" and doesn't give me an option to change the Forge version, only the Minecraft version. The error is "Manifest: NOSIGNATURE".

**Comment by walksanatora** [comment]
i would recommend asking in the forge discord as that is a fml crash

**Comment by fnuecke** [comment]
> Caused by 1: java.lang.NoClassDefFoundError: li/cil/manual/api/prefab/item/AbstractManualItem

Ah, looks like you're missing the markdown manual mod dependency on the server. It's mistakenly marked as a client only dependency in the mod definition, hence no proper error message on that, sorry about that.
