### ISSUE TITLE
Ability to scroll in code bibles

### ISSUE THREAD

**Issue by walksanatora** [MightyPirates/TIS-3D#167]
currently the vanilla book is a more effective tool for programming in TIS-3D as it allows you to write programs that are more then 20 lines long (despite normal server config allowing for 40 lines of execution)
this could (or probally would) be implemented along side #158

**Comment by walksanatora** [comment]
another possible solution could be a way to "link" pages so that it basically combines them one after the other

**Comment by walksanatora** [comment]
i just bound out the `#BWTM` pre-processor exist
**why is this not documented in the book**

**Comment by walksanatora** [comment]
(along with the mutiple redstone sources making execution faster)

**Comment by fnuecke** [comment]
The multi-page macro is documented [in the code bible page](https://github.com/MightyPirates/TIS-3D/blob/b51487225cec7f34f0f9ce1fc59a2b0a8c3aa8f4/src/main/resources/assets/tis3d/doc/en_us/item/code_book.md). The "overclocking" is hinted at in the [main manual page](https://github.com/MightyPirates/TIS-3D/blob/b51487225cec7f34f0f9ce1fc59a2b0a8c3aa8f4/src/main/resources/assets/tis3d/doc/en_us/index.md).
