### ISSUE TITLE
[question] why no modules on the controller

### ISSUE THREAD

**Issue by walksanatora** [MightyPirates/TIS-3D#168]
there have been a few fimes where i have pondered "why no modules on the controller" i was unnable to find a issue asking this question so i would just like to ask it here for ""documentation""

**Comment by fnuecke** [comment]
More fitting for the Discussions area, but: one of the main design goals in this mod was to keep things "orthogonal", i.e. avoid overlap in behavior of different things. Making the controller behave like a casing *and* the "heart" of the computer would go against this. Makes it clearer and easier to understand/explain what does what this way. Also would make the code more complex and error prone.
