### ISSUE TITLE
Lan multiplayer displays dont update unless person killed

### ISSUE THREAD

**Issue by Heketiitus** [MightyPirates/TIS-3D#172]
we play multiplayer i see the displays correctly displaying contents but other person doesnt see the contents update until /killed.
the other person goes to singleplayer world and it works for him its not issue of computer its issue of multiplayer.

**Comment by B4CKU** [comment]
i've had a similar issue on my end. what other mods were you using? @Heketiitus

**Comment by idkjanevim** [comment]
I have the same problem on my server. When my friend is online, I can't see anything on any module, but when he disconnects, I can see everything fine.

**Comment by Heketiitus** [comment]
> i've had a similar issue on my end. what other mods were you using? @Heketiitus

i was only using jei. also its the forge version
