### ISSUE TITLE
Why custom raycast when it is allready implemented in mc

### ISSUE THREAD

**Issue by walksanatora** [MightyPirates/TIS-3D#174]
Yes another question while fixing ValkrienSkies conpat (as my sanity dwindles yet more)

**Comment by fnuecke** [comment]
Presumably because this didn't exist back when it was originally implemented (at least not in the way it was needed).  A PR to switch to the built-in logic while preserving current behavior is welcome!

**Comment by walksanatora** [comment]
huh i have a mixin just for this (i converted your raycast to a mixin for VS2 so that Infared Packets could work on ships)

**Comment by walksanatora** [comment]
all i had to do was create a custom ClipContext and overrde `getBlockShape`
what i ended up doing was getting a Boolean AND of the block collision + Visual shape
