### ISSUE TITLE
Feature Suggestion: Pocket Terminal

### ISSUE THREAD

**Issue by dther** [MightyPirates/TIS-3D#175]
Minor spoilers for TIS-100's post-game campaign and Mobius Front ahead.

Given the lore of the TIS-100 is that TIS systems utilise quantum trickery + radio waves to transmit data across different points in spacetime, I'd love to see some kind of "Pocket Terminal" item that can be bound and used to interact with one specific Terminal module. There's precedent for this in Mobius Front, even- the TIS radio controller is some kind of signal decoder for text packets sent over radio, and works across portals to different universes.

**Comment by fnuecke** [comment]
I'm afraid I still have PTSD from OC's tablet computers and terminals (exaggerating, but only slightly).  So I'd rather not, sorry.
