### ISSUE TITLE
Invisible Terminal Input 

### ISSUE THREAD

**Issue by 9Octopus** [MightyPirates/TIS-3D#179]
![image](https://user-images.githubusercontent.com/69008304/226488304-8b606a0a-c618-418d-b055-3d60e96f3608.png)

**Comment by fnuecke** [comment]
not enough info

**Comment by dragonmaus** [comment]
For future reference, this is probably related to having Sodium installed.

Essentially, Sodium prevents any text from rendering on the terminal screen; when you type, it moves the cursor but only leaves blanks behind.

**Comment by ImUrX** [comment]
And is there any fix for that aside from disabling sodium?
