### ISSUE TITLE
Shaders Visual Bug 

### ISSUE THREAD

**Issue by 9Octopus** [MightyPirates/TIS-3D#180]
![image](https://user-images.githubusercontent.com/69008304/226488475-15766752-90e1-43c5-8a71-5a830a7a2144.png)

Using Oculus / Rubidium
Shaders tried 
BSL/Astralex
Complimentary/Reimagined/Reimagined Voxels

SEUS is slightly improved, but still not correct
![image](https://user-images.githubusercontent.com/69008304/226488704-67b437f2-6760-41a6-acb0-71bd7af620b3.png)

The bottom casing has an execution module on the front and a redstone module on the right

**Comment by atik1n** [comment]
As I remember, it's the same issue as on OpenComputers on OptiFine shaders

**Comment by fnuecke** [comment]
I'm afraid I don't have the time to ensure shader compatibility.  That said, I don't think the casing rendering does anything esoteric, so I wouldn't even know where to start.  PRs helping with this would be appreciated, of course.

**Comment by OwOday** [comment]
any workaround?

**Comment by beeeeeeeeean** [comment]
> I'm afraid I don't have the time to ensure shader compatibility. That said, I don't think the casing rendering does anything esoteric, so I wouldn't even know where to start. PRs helping with this would be appreciated, of course.

Replacing the custom renderType (atlas_module_overlay) with a vanilla one renders the modules correctly. Internally, the shader receives a UV 1.0, 1.0 for every vertex. I briefly looked at Applied Energistics 2's custom renderTypes (used for drives and drive LEDs) though I didn't see aything much different
