### ISSUE TITLE
[1.7.10] Non-working Casings cause FPS drops

### ISSUE THREAD

**Issue by Alex-1248** [MightyPirates/TIS-3D#181]
Minecraft 1.7.10
Forge 10.13.4.1614
TIS-3D-MC1.7.10-1.4.0.78

Casings cause a significant FPS drop when they are in view. In a super flat world, 64 Casings drop FPS from 300 to 100 when I turn towards them. Controllers, having a similar shape, do not have a noticeable effect on FPS. Is it normal that non-working empty Casings create such a load?

This problem is not present in the first versions of the mod for 1.7.10. The latest version without this problem is 0.6.0.40. The first version with this problem is 0.6.1.43.

**Comment by fnuecke** [comment]
I'm afraid I don't have the time to support older versions.  That said, casings do use a slightly more complex tile/block entity renderer for module rendering, so some overhead is to be expected as opposed to the controller one.
