### ISSUE TITLE
[1.7.10] Under certain conditions, the Redstone Module does not receive a redstone signal

### ISSUE THREAD

**Issue by Alex-1248** [MightyPirates/TIS-3D#182]
Minecraft 1.7.10
Forge 10.13.4.1614
TIS-3D-MC1.7.10-1.4.0.78

Steps to reproduce:

1. Install Casing with Redstone Module and Controller with lever. There must be a distance of at least one block between Casing and Controller. Connect them using empty Casings. Place the redstone dust next to the Redstone Module and place the lever next to the redstone dust.
2. Turn on the computer.
3. Turn on the lever next to the redstone dust. The Redstone Module will respond to the signal.
4. Turn off the computer.
5. Turn on the computer.

Expected result: The Redstone Module will respond to the redstone dust signal.
Actual result: Redstone Module looks like there is no signal and sends 0 to other Modules even though redstone dust is glowing. In order for the Redstone Module to receive the redstone signal, Casing must receive a Block Update after the computer is turned off.

**Comment by fnuecke** [comment]
Thanks for reporting!  I'm afraid I don't have the time to support older versions anymore, but it's fixed in the new ones.
