### ISSUE TITLE
[1.7.10] Two bugs in Terminal Module

### ISSUE THREAD

**Issue by Alex-1248** [MightyPirates/TIS-3D#183]
Minecraft 1.7.10
Forge 10.13.4.1614
TIS-3D-MC1.7.10-1.4.0.78

1. This module cannot be crafted. The module is present in NEI, but its recipe cannot be obtained. Also, it was not possible to craft it using the recipe from Mc 1.10.2.
2. When I move a few blocks away from the installed Terminal Module, its screen is replaced by a texture consisting of black and pink squares.

**Comment by fnuecke** [comment]
Thanks for reporting, seems I misunderstood how advancement requirements work back when I added this.
The render thing I would assume is a broken texture back in that version.
However, as mentioned in the other ticket, I'm afraid I don't have the time to support older versions, sorry.
