### ISSUE TITLE
[1.7.10] Missing information in the Reference Manual

### ISSUE THREAD

**Issue by Alex-1248** [MightyPirates/TIS-3D#184]
Minecraft 1.7.10
Forge 10.13.4.1614
TIS-3D-MC1.7.10-1.4.0.78

The Reference Manual does not mention:
1. Multiplication (MUL) and division (DIV) commands.
2. Manual editing of the ROM Module.

**Comment by fnuecke** [comment]
This info is in the current versions of the manual, afraid I don't have the time maintain old versions.
