### ISSUE TITLE
[1.19.2] net.minecraft.client.OptionInstance becomes final

### ISSUE THREAD

**Issue by SigmaFlame** [MightyPirates/TIS-3D#188]
The game crashed whilst initializing game
Error: java.lang.IncompatibleClassChangeError: class net.coderbot.iris.gui.option.ShadowDistanceOption cannot inherit from final class net.minecraft.client.OptionInstance

You mod in 1.19.2 (Tis-3D) makes the class net.minecraft.client.OptionInstance as final, so other mods cannot inherit on it.
You mod is incompatible with Oculus.

**Comment by fnuecke** [comment]
I don't see how TIS-3D would be doing this.  I'm almost exclusively using mixins for the mods own classes for fabric/forge cross compatibility.  Nothing touches this class from what I can see.
