### ISSUE TITLE
Mod gives a ResourceLocationException error

### ISSUE THREAD

**Issue by Berkvrl** [MightyPirates/TIS-3D#193]
I'm using the 1.19.2 version of this mod. When opening the game this mod gives a "net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: tis3d:casingınventory" error. I suppose it's because of a language error if you forced this mod to use an en-US (or similar) locale this issue will be fixed.

**Comment by fnuecke** [comment]
Cannot repro, attempted to blind fix.  Can only guess where this was.  For future reports, please also provide the mod version, thanks :)

**Comment by Berkvrl** [comment]
I was using 1.7.3 version of this mod. My pc uses a turkish locale thats why you can't reproduce this issue. Since java uses a pcs default locale when switching between lowercase and uppercase letters I think in US or EN locales works fine.Most of the time the letter I is the issue in English you only have one I but in turkish we have two of them (I,ı and İ,i).

**Comment by fnuecke** [comment]
Right, then the blind fix should be it!  Thanks for reporting and the extra info :)
