### ISSUE TITLE
ADD 1 stuck at 0x7FFF

### ISSUE THREAD

**Issue by lanc12** [MightyPirates/TIS-3D#204]
`ADD 1` can usually be used to well... add 1, but once you reach `0x7FFF`, `ADD 1` no longer works and just gets stuck.

This is a problem for programs that use and manipulate large numbers. Why this occurs? No idea, sorry.

Version: `tis3d-MC1.20.1-forge-1.7.7+354a583.jar`
Loader: `NeoForge 1.20.1 47.1.104`

Look, I know it's unsupported in this version, but usually Forge mods work fine under NeoForge.

**Comment by KarolOfGutovo** [comment]
This isn't an issue, 0x7FFF corresponds to the highest value and 0x8000 is the lowest negative value. The behavior of not overflowing is questionable, but it is what it is.
