### ISSUE TITLE
Audio module

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/TIS-3D#27]
Built using a noteblock, emits noteblock sounds based on input value (no square wave gen - at least for now).

Something like `0xFF00` masks pitch, `0x00FF` masks note type or so.

**Comment by Vexatos** [comment]
:trumpet: :loud_sound: :loudspeaker: :bell: :musical_note: :notes: :musical_keyboard: :musical_score:

**Comment by ds84182** [comment]
🎺🎺🎺🎺
