### ISSUE TITLE
Visual bug if you break the connection to the controller

### ISSUE THREAD

**Issue by feldim2425** [MightyPirates/TIS-3D#32]
If you apply a redstone signal to the controller and break the casing that connects to the controller it looks like the tis is still turned on, but it doesn't execute commands.
The modules also doesn't update if you put the casing back, only if you remove the redstone signal from the controller after replace the missig casing.

![](https://i.imgur.com/3KyNCKk.png)
In this picture I removed the casing above the Keypad Module

**Comment by fnuecke** [comment]
Thanks! Splits weren't really handled until now, works as it should now.
