### ISSUE TITLE
Don't send state info on execution module if invisible

### ISSUE THREAD

**Issue by fnuecke** [MightyPirates/TIS-3D#35]
That is, if there's a fully opaque cube in front of an execution module, don't send state changes, but do send one when that block breaks to get in sync again. This could avoid sending a *lot* of unnecessary but frequent packets.

**Comment by Vexatos** [comment]
@fnuecke Maybe break the API yet again (yay) to give the method `render()` a parameter whether it's visible as well as a way to get whether a module is currently visible through `getController()`?

**Comment by fnuecke** [comment]
I was thinking more of a helper method in `AbstractModule` that checks if (pseudo) `isSideSolid(getFace().getOpposite())` is true. Not sure if that'd gain much rendering-speed-wise. Would need testing.

**Comment by Vexatos** [comment]
@fnuecke Well probably not unless you're drawing dozens of things. But if the packets are only sent for rendering purposes, it would be extremely useful for packet efficiency.

**Comment by fnuecke** [comment]
Exactly.
