### ISSUE TITLE
Display module insufficiently esoteric

### ISSUE THREAD

**Issue by MrEldritch** [MightyPirates/TIS-3D#37]
Drawing entire rectangles individually with a single call? Come on, where's your spirit of adventure? 

Why not simply use something like the original TIS-100 display protocol, starting at an X and Y coordinate and drawing a horizontal sequence of colors until you hit a stop? 

Yes, it would be clunky and difficult to use, but I thought that was sort of the point - to create an extremely flexible computing system more powerful than regular redstone, which nonetheless required solving TIS-100-like puzzles to use, because they naturally arose through the peculiar architecture. There really aren't enough mods that are puzzles to use in and of themselves.

**Comment by skyem123** [comment]
But this would break existing builds...

**Comment by MrEldritch** [comment]
Honestly, given the relative obscurity of TIS-100, the fact that the display module isn't terribly useful, and the short time the mod's been out for, I assumed there weren't enough existing builds to worry about breaking.

Certainly I'd never suggest a major change in basic functionality on a more established mod.

**Comment by skyem123** [comment]
Hmm... what about the possibility of having two different "modes" of the screen? (can be switched by shift right clicking?)
Then the harder mode could have a "reward" for it, such as a higher resolution?

**Comment by MrEldritch** [comment]
I dunno, having two entirely different protocols simultaneously seems like it'd be a lot of work for the dev. I mean, it might not be, I don't know.

**Comment by fnuecke** [comment]
There are already a good number of differences to TIS-100 (such as the number range or the existence of bitwise operations). The fact that this behaves differently to the way TIS-100's visualization nodes work was deliberate, to avoid spamming network packets even more than the mod already does. Sending a packet for each changed pixel when it's more practical to just draw a larger rectangle anyway just isn't a very sane option. Plus while the how is still a large part of the fun in TIS-3D, being able to actually do something useful with it is more important than in TIS-100 ;-)

**Comment by MrEldritch** [comment]
I understand. The number range and existence of bitwise operations seemed pretty necessary to me to do anything useful with redstone and real control situations at all; I don't begrudge you those in the least.

I think I'd prefer the TIS-100 display style nonetheless, because various impressive examples of TIS-100 sandbox code have shown that you really _can_ do useful stuff with it (Pong! A drawing program! Arbitrary image display! Sprites!) but if it'd spam network packets (which I guess it would, because it would only draw one pixel at a time) I understand completely. Sorry to bother you!
