### ISSUE TITLE
Crash when run with SpACore mod

### ISSUE THREAD

**Issue by Faeranne** [MightyPirates/TIS-3D#39]
http://paste.ee/p/aVImZ

Both SpACore and TIS-3D run fine alone, but not at the same time.  Appears to be an ASM error.  I'm also posting to SpACore as well.

**Comment by Faeranne** [comment]
SpACore issue:
https://github.com/specialattack/SpACoreForge/issues/7

**Comment by fnuecke** [comment]
As mentioned in the linked issue, problem was caused by outdated ASM running on the TIS-3D classes (which are Java 8).
