### ISSUE TITLE
Crash with Redlogic

### ISSUE THREAD

**Issue by empiricist** [MightyPirates/TIS-3D#40]
Trying to use the Bundled Redstone Module with a Redlogic bundled cable crashes the game.  

[log here](http://pastebin.com/zAA6X5i0)

To replicate: Place controller and casing block.  On the casing, place a Bundled Redstone Module.  Next to bundled module, place a Redlogic bundled cable with at least one signal nonzero.  Activate the controller, and the game will immediately crash.  

This problem does not seem to occur with freestanding bundled cables, but I cannot extract values from them either so that is probably just because TIS-3D does not recognize them as bundled cables.

**Comment by fnuecke** [comment]
Thanks for the reminder, this has actually been fixed a while ago, I just completely forgot to push 0.8.2 to Curse and co :P

For now, grab the latest build from [Jenkins](http://ci.cil.li/view/TIS-3D/).
