### ISSUE TITLE
Bug: Z-fighting when modules are displayed as items on block surfaces

### ISSUE THREAD

**Issue by Techokami** [MightyPirates/TIS-3D#47]
Quite simply, if you use something to display blocks as items on another block (Bibliocraft shelves in fast mode, Storage Drawers drawers in fast mode, Applied Energistics 2 displays), using them to show TIS-3D modules will result in the module Z-fighting with itself.

Have a screenshot:
![2016-04-09_18 17 48](https://cloud.githubusercontent.com/assets/1530728/14407222/ca606794-fe8e-11e5-9589-3c1e0b0b9cd8.png)

**Comment by fnuecke** [comment]
1.8.9? In that case I blame @Vexatos :P He PRed the layered rendering, I have no idea how that works.

**Comment by Vexatos** [comment]
@fnuecke me neither.

**Comment by fnuecke** [comment]
\o/

Wait, how did you do it then :X

**Comment by fnuecke** [comment]
But yeah, before we dig into this, please let us know the MC, TIS-3D and Computronics versions you're using.

**Comment by Techokami** [comment]
Oh, sorry, forgot to mention those.
Minecraft 1.7.10, TIS-3D 0.8.4-64, Computronics 1.6.1 (as of when Vex fixed Iron Note Blocks)

**Comment by fnuecke** [comment]
Sorry, but I just won't get around to updating the 1.7.10 version anymore :/
