### ISSUE TITLE
duplicate controller block id with AppliedEnergetics

### ISSUE THREAD

**Issue by 0Navis0** [MightyPirates/TIS-3D#50]
I get this crash with the first AE2 1.10.2 version, it seems that you both use the same id for the controller block. http://pastebin.com/kRQj6e3s

**Comment by shartte** [comment]
We both failed to properly namespace the tile entity ID.

**Comment by yueh** [comment]
Why the heck is forge not doing it just like with blocks and items?

**Comment by shartte** [comment]
I think the ids are not mapped to numerical ids for save and network
purposes. This means there is some overhead for longer ids.

Both our mods will have to switch to fully unique names though.

**Comment by fnuecke** [comment]
Wait, TEs aren't auto-namespaced? Well shit. Will change that then.

**Comment by fnuecke** [comment]
8a0ddd8

**Comment by fnuecke** [comment]
New version is on Curse.
