### ISSUE TITLE
Could you make a wiki for this mod? 

### ISSUE THREAD

**Issue by vlad1vv1** [MightyPirates/TIS-3D#66]
Hi, your mod really liked. But I only start programming on the assembler. Could you make a wiki for this mod? I for example played in Steam TIS-100. There I like everything as understood. But here's how to work with the additional blocks of your mod - not very good. 

Write short examples of ready-made programs on the use of blocks, please. 
How to use the music block, ROM, RAM, keyboard, terminal.

It is necessary to show well, can make a guide? Types of examples:

- sound, melody, give an example of the program, what to do with the addresses that you indicated is not known. Values ​​can be entered in the HEX form? Or in DEC. Are they fixed in step?

- keyboard, How are symbols input?

- timer, need an example.

- terminal, for what possible ideas does the terminal need, what should we do with these labels? Do you want to write to the executable from it?

**Comment by fnuecke** [comment]
Sorry, I'm quite happy with the manual, which doubles as a "wiki" (as it can be [viewed via this repository](https://github.com/MightyPirates/TIS-3D/blob/master-MC1.11/src/main/resources/assets/tis3d/doc/en_us/index.md), and people could contribute to it via pull requests). So no, no separate wiki. Examples aren't really necessary IMHO, what the modules do is well documented, and some trial and error will allow you to very quickly figure out what they do anyway.

As for your questions, those are IMHO either directly addressed in the manual or really easily tested by trial and error:
- Audio module: as mentioned in the manual, those are bitmasks, when a packed value is received by the module, the sound is played, same rules as with any other module). 
- Keypad: just have one next to a stack or so, and you'll see it just outputs the numbers input.
- Timer: what it does and how to use it is described in the manual. Just test it by sending a value in and see what it outputs.
- It's just a more powerful version of the keypad, combined with a more specific (but potentially easier to use) display module. Useful for quickly writing stuff to RAM modules e.g.
