### ISSUE TITLE
Question on the Redstone Bundle module.

### ISSUE THREAD

**Issue by vlad1vv1** [MightyPirates/TIS-3D#67]
Honestly, we do not really know what this module is for? To connect some kind of connections? Which ones? Perhaps this is because of the difficulties of translation.
MOV 0XFF ACC
SHL 8 # HI = 0xFF( Shifted the bit to the left by 9 points, for what?) HI = 0xFF(Why did the same meaning remain the same?)
ADD 6 # LO = 6
MOV ACC LEFT

Here, channel 9 is open and assigned a value of 7? Is it the strength of the red signal? Explain, please. What's next? Need an example or a guide for practical use.

**Comment by fnuecke** [comment]
`HI` refers to the high byte, `LO` to the low byte, so `0xFF << 8` -> `0xFF00`.
As mentioned in the manual, `0xFFYY` means channel `YY` is selected, so no, no channel is assigned a value here (where'd you get the 9 from btw?), the 7th channel is selected for input. So when reading from the module, whatever the 7th channel's input currently is will be output by the bundled redstone module.

For any other `0xYYZZ` channel `YY`'s output will be set to `ZZ`. So `0x06FF` will set the 7the channel to output the maximum value of 255.

Do note that currently only charset wires bundled redstone is implemented, I'll look into adding Project Red and EnderIO support again when I can, just be aware of that.
