### ISSUE TITLE
Execution module not working as intended

### ISSUE THREAD

**Issue by Player505** [MightyPirates/TIS-3D#72]
The execution module isn't working as intended to the best of my knowledge. From what I can see in the [code](https://imgur.com/srKpLrL) that I have written, if an input from the 'up' side is equal to 4 then there should be an infinite loop of an output of 15 to the 'right' (on the right side of the block is a redstone module). However, as it stands it seems to send an [output](https://imgur.com/tDW6Ljg) for one cycle and then jumps back to the [start](https://imgur.com/JuPBEpt)? I tried to get just the two lines that were the infinite loop on another execution module and it seemed to work fine.

Forge version 
1.12.1-forge1.12.1-14.22.1.2478

Mods
BetterPlacement-1.0.0-1
CTM-MC1.12-0.2.2.7
ImmersiveEngineering-0.12-72
ImmersiveEngineering-0.12-72-core
immersivepetroleum-1.12-1.1.3
jei_1.12-4.7.5.85
OpenComputers-MC1.12.1-1.7.0.4
OptiFine_1.12.1_HD_U_C5
TIS-3D-MC1.12-1.2.4.8
worldedit-forge-mc1.12-6.1.8-dist

**Comment by fnuecke** [comment]
Can't reproduce that, loops as expected.
- What does your full setup look like?
- Does it also happen if you have just one casing (with say a keypad on top and something like an IR module right and bottom to consume outputs)?
- Does it also happen with just TIS-3D?
- Do you maybe cycle the controller's power somehow?

**Comment by Player505** [comment]
I'm sorry but it looks like my issue was caused by me. The problem I had was that I had multiple Redstone modules touching each other which caused weird stuff. Sorry again about this

**Comment by fnuecke** [comment]
Ah, that'd explain it yes :) No worries. Just in case you don't know, you can lock data transfer across specific edges using the keys while sneaking.

**Comment by Player505** [comment]
I didn't know that. Thanks for the tip :)
