### ISSUE TITLE
Execution modules on the bottom not working with orientation correctly.

### ISSUE THREAD

**Issue by prozacgod** [MightyPirates/TIS-3D#74]
![2017-09-26_21 53 08](https://user-images.githubusercontent.com/67706/30893724-55ffa0e6-a305-11e7-9216-b18e604808fc.png)

I was able to access down as up & up as down in these modules, they work and execute just fine, but you have to install them opposite the expected way.

**Comment by fnuecke** [comment]
Thanks. This should be fixed in the [latest dev build](http://ci.cil.li/job/TIS-3D-MC1.12/), just want to do some more testing before pushing to Curse again (because I ran into a bug right after uploading it yesterday, as always).
