### ISSUE TITLE
redstone module not latched value from opcode.

### ISSUE THREAD

**Issue by Diukenukem** [MightyPirates/TIS-3D#77]
Sorry for my english. I need precision of blocks activation side by side. Tis 3d it's fantastic for this, but i can acivate only for 1 opcode executing time. Please, if switched options for redston module it's problem. Maby create anoter module, latched redstone module?

**Comment by fnuecke** [comment]
Sorry, I don't quite understand what exactly the issue is. Could you provide a step-by-step build (and/or screenshots) to reproduce the problem? Thanks.

**Comment by fnuecke** [comment]
Closing this due to lack of feedback.
