### ISSUE TITLE
Rendering crash with multiple controllers

### ISSUE THREAD

**Issue by esotericist** [MightyPirates/TIS-3D#81]
I was stacking controllers because it was the block I had in hand for getting scale, and this happened:
[crash-2018-07-16_19.23.08-client.txt](https://github.com/MightyPirates/TIS-3D/files/2199914/crash-2018-07-16_19.23.08-client.txt)

Forge 2705, TIS-3D-MC1.12-1.3.1.17, ImmersiveRailroading-1.2.1_1.12, trackAPI-1.1_1.12, no other mods present (but I don't think anything but TIS-3D matters here, nothing else was in view)

**Comment by fnuecke** [comment]
Ah, this could happen when controllers in an errored state were in view and the player then was looking at a regular entity (monster, animal, etc). Thanks for reporting this!

**Comment by esotericist** [comment]
I was pretty sure in that case I was just pillaring with controllers. I don't think any other entities were in view at the time

**Comment by fnuecke** [comment]
Hm, the error basically was if the player is looking at something the block pos of that info object not being set. Which was 100% reproducible with entities. Should always be set when the looked-at thing is a block, which is what I'm checking for now.

**Comment by esotericist** [comment]
Well, I'll take your word for it. I'm trying to limit how much of how minecraft works internally I have to learn. :) Will this also fix #80?

**Comment by fnuecke** [comment]
Good choice for staying sane :)

And nope, needs a separate fix, but same issue basically, true. Will be up in a moment.
