### ISSUE TITLE
unusable (Rift Version)

### ISSUE THREAD

**Issue by edbefee3-3888-462a-9411-741b7e9eb54e** [MightyPirates/TIS-3D#85]
the game don't run at all with this mod

**Comment by asiekierka** [comment]
Are you using OptiFine?

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
nope

**Comment by asiekierka** [comment]
What's the problem, then? You weren't very specific.

**Comment by edbefee3-3888-462a-9411-741b7e9eb54e** [comment]
I start the game and instead of it running I see "Game Crashed" message

**Comment by asiekierka** [comment]
Could you please try to find a more detailed console log?

**Comment by Octr** [comment]
https://pastebin.com/xPFkbEU8 (Log)

**Comment by asiekierka** [comment]
Rift is no longer supported by any modder, I think, so I also think it's fair that this be dropped. Sorry!
