### ISSUE TITLE
[Fabric] crash on placing controller

### ISSUE THREAD

**Issue by spyguy26** [MightyPirates/TIS-3D#88]
using:
TIS-3D-MC1.14-Snapshot-Fabric-1.5.0.1
fabric-0.1.5.88
mapping/game: 19w05a.6
loader: 0.3.5.106

when placing a controller down into the world the game instantly crashes
here's the log https://gist.github.com/spyguy26/5999405707b5a8213f764b07987ab167

**Comment by asiekierka** [comment]
Yep, TIS-3D needs a snapshot update. Larger mods will need it every so often. As I insist, snapshots are for developers - not users

**Comment by fnuecke** [comment]
New build for 19w05a, Fabric 0.1.5.88 is up.
