### ISSUE TITLE
TIS-3D registers its textures to just every existing texture map without checking whether it's the correct one.

### ISSUE THREAD

**Issue by CD4017BE** [MightyPirates/TIS-3D#94]
see: MightyPirates/OpenComputers#3094

**Comment by asiekierka** [comment]
There's quite a lot of mods doing this, mind, and I don't blame them - this is only properly accounted for by vanilla in 1.14.

**Comment by CD4017BE** [comment]
> this is only properly accounted for by vanilla in 1.14

No, it's rather that vanilla on its own doesn't use more than one TextureMap instance, so some modders blindly assume that the TextureMap given in the TextureStitchEvent is always the blocks texture map.

**Comment by CD4017BE** [comment]
Ok, I think getting this fixed by other mods is hopeless:

```
[17:04:34] [Client thread/FATAL] [rs_ctr]: The following mods attempted to register textures into a texture atlas they don't belong:
- cofh
- industrialforegoing
- buildcraftlib
- powersuits
- immersiveengineering
- thermaldynamics
- buildcraftsilicon
- buildcraftenergy
- buildcrafttransport
- genetics
- bibliocraft
- thermalfoundation
- ic2
- buildcraftbuilders
- reborncore
- topaddons
- buildcraftfactory
- appliedenergistics2
- blockcraftery
- ae2stuff
- railcraft
- thermalexpansion
- xreliquary
- buildcraftcompat
- chisel
- computercraft
- ftblib
- flatcoloredblocks
- thaumcraft
- peripheralsplusone
- forge
- mysticallib
- twilightforest
- chiselsandbits
- buildcraftcore
- techreborn
- magicbees
- forestry
- extratrees
Modders please check whether the TextureMap given in texture stitch event is actually the one you want to register to!
```

**Comment by asiekierka** [comment]
>No, it's rather that vanilla on its own doesn't use more than one TextureMap instance, so some modders blindly assume that the TextureMap given in the TextureStitchEvent is always the blocks texture map.

Because that is the case in vanilla.

Really, just, make your own stitch, event, and block Forge's from emitting
