### ISSUE TITLE
[1.14-fabric] Crashes almost instantly when loading up

### ISSUE THREAD

**Issue by apotheoseGrifter** [MightyPirates/TIS-3D#96]
As the title says.

In case it's relevant, I tested this on a new MutiMC instance, mappings 1.14.2+build.2 and loader version 0.4.8+build.154, with no other mods except Fabric API version 0.3.0+build.175 and TIS-3D version MC1.14.2-Fabric-1.5.0.9-dev. I also attempted it with every single build of Fabric API 0.3.0 down to 158. No dice, and as far as I can tell the exact same error every time.

As a side note, I believe I got the same or similar error the last time I tried to use TIS-3D on Fabric, though that time I assumed it was just because it was outdated for the Fabric version I was using.

EDIT: Oops, forgot to actually post the error log.

https://paste.ee/p/GXLUM

**Comment by Jcat4609** [comment]
Bit of an update:

This appears to be a bug with 1.14.1-fabric and 1.14.2-fabric.
Using 1.14-fabric allows TIS-3D to load perfectly normal.

[1.14 Log](https://paste.ee/p/WzyAf)
[1.14.1 Crashlog](https://paste.ee/p/Wy0Vq)
[1.14.2 Crashlog](https://paste.ee/p/qe7cF)
(removed ModMenu to look for incompatibilites in 1.14.2, does nothing to alleviate problem)

As I have no ability to mod for 1.14.x, I can't propose any changes - best of luck Mighty!

**Comment by asiekierka** [comment]
The mod has been updated.
