### ISSUE TITLE
Crash to Desktop on 1.14.4 fabric

### ISSUE THREAD

**Issue by prozacgod** [MightyPirates/TIS-3D#97]
When placing any of the modules into the frame, I get crashes

I had the issue in a configuration that had a few mods, so I created a new instance in MultiMC - installed fabric, relaunched - added tis3d 

crash log:

https://paste.ee/p/ZysKo

**Comment by asiekierka** [comment]
Yes, TIS-3D was last updated to 1.14.3, and 1.14.4 broke it.

**Comment by asiekierka** [comment]
https://github.com/MightyPirates/TIS-3D/commit/19e383052b569167218545d6201702f45f58f11a
